@startuml
title 系統架構圖
left to right direction


[Client] as ClientComp

[Nginx] as ProxyComp

frame "DcardServer1" as Server1Comp {
  [RateLimiter] as RateLimiter1
}

frame "DcardServer2" as Server2Comp {
  [RateLimiter] as RateLimiter2
}

database "Redis" as Cache {

}

ClientComp --> ProxyComp
ProxyComp --> RateLimiter1
ProxyComp --> RateLimiter2
RateLimiter1 <--> Cache
RateLimiter2 <--> Cache
@enduml