server:
  host: 0.0.0.0
  port: 8080
  healthcheck: /ping
  mode: debug
log:
  app_name: dcard-hw
  level: debug
  env: dev
limiter:
  type: leaky_bucket
  period_sec: 60
  request_count: 60
  redis:
    host: 127.0.0.1
    port: 6379
    db: 2